Repository happymanwon/Backend, pull requests merged in 2023-12, with the labels that each got.

#16 [Function] 서울 착한 가격 업소 조회 수정 : 위도,경도,도로명주소 추가 및 localCode 검색 기능
  build.gradle
  src/main/java/org/hmanwon/domain/shop/application/ShopService.java
  src/main/java/org/hmanwon/domain/shop/dao/LocalCodeRepository.java
  src/main/java/org/hmanwon/domain/shop/dto/SeoulGoodShopResponse.java
  src/main/java/org/hmanwon/domain/shop/entity/LocalCode.java
  src/main/java/org/hmanwon/domain/shop/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/shop/exception/ShopExceptionCode.java
  src/main/java/org/hmanwon/domain/shop/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/shop/init/dto/AddressDto.java
  src/main/java/org/hmanwon/domain/shop/init/dto/FirstJsonReadDto.java
  src/main/java/org/hmanwon/domain/shop/init/dto/ItemDto.java
  src/main/java/org/hmanwon/domain/shop/init/dto/SeoulGoodShopDto.java
  src/main/java/org/hmanwon/domain/shop/init/util/AddressToCodeConverter.java
  src/main/java/org/hmanwon/domain/shop/init/util/KakaoApiUtil.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/resources/application.yml
  src/main/resources/seoul_good_shop.json
Labels: Type: Feature/Function

#19 [fix] KakaoApiUtil 수정
  src/main/java/org/hmanwon/domain/shop/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/shop/init/util/KakaoApiUtil.java
Labels: Type: Hotfix

#18 [fix] responseDTO 수정
  src/main/java/org/hmanwon/domain/community/comment/presentation/CommentRestController.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/java/org/hmanwon/global/common/dto/ResponseDTO.java
Labels: Type: Feature/Function

#20 [Feat] 짠처리 기능 구현
  build.gradle
  src/main/java/org/hmanwon/domain/member/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/member/entity/Member.java
  src/main/java/org/hmanwon/domain/shop/dto/SeoulGoodShopDetailResponse.java
  src/main/java/org/hmanwon/domain/shop/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/shop/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/zzan/purchase/application/PurchaseService.java
  src/main/java/org/hmanwon/domain/zzan/purchase/dao/PurchaseHistoryRepository.java
  src/main/java/org/hmanwon/domain/zzan/purchase/dao/QrImageRepository.java
  src/main/java/org/hmanwon/domain/zzan/purchase/dto/PurchaseResponse.java
  src/main/java/org/hmanwon/domain/zzan/purchase/dto/PurchaseResultResponse.java
  src/main/java/org/hmanwon/domain/zzan/purchase/entity/PurchaseHistory.java
  src/main/java/org/hmanwon/domain/zzan/purchase/entity/QrImage.java
  src/main/java/org/hmanwon/domain/zzan/purchase/exception/PurchaseException.java
  src/main/java/org/hmanwon/domain/zzan/purchase/exception/PurchaseExceptionCode.java
  src/main/java/org/hmanwon/domain/zzan/purchase/exception/QrCodeException.java
  src/main/java/org/hmanwon/domain/zzan/purchase/exception/QrCodeExceptionCode.java
  src/main/java/org/hmanwon/domain/zzan/purchase/presentation/PurchaseController.java
  src/main/java/org/hmanwon/domain/zzan/purchase/type/PurchaseStatusType.java
  src/main/java/org/hmanwon/domain/zzan/purchase/util/QRCodeUtil.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/application/ZzanService.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/dao/ZzanItemRepository.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/dto/ZzanItemDetailResponse.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/dto/ZzanItemResponse.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/entity/ZzanItem.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/exception/ZzanException.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/exception/ZzanExceptionCode.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/presentation/ZzanController.java
  src/main/java/org/hmanwon/domain/zzan/zzanItem/type/SaleStatus.java
Labels: Type: Feature/Function, Status: In Progress

#23 Feature/member api
  build.gradle
  src/main/java/org/hmanwon/domain/auth/application/AuthService.java
  src/main/java/org/hmanwon/domain/auth/application/JwtProvider.java
  src/main/java/org/hmanwon/domain/auth/dto/AuthLoginResponse.java
  src/main/java/org/hmanwon/domain/auth/presentation/AuthController.java
  src/main/java/org/hmanwon/domain/community/board/application/BoardService.java
  src/main/java/org/hmanwon/domain/community/board/dto/response/BoardDetailResponse.java
  src/main/java/org/hmanwon/domain/community/board/dto/response/BoardResponse.java
  src/main/java/org/hmanwon/domain/community/board/entity/BoardHashtag.java
  src/main/java/org/hmanwon/domain/community/board/exception/BoardExceptionCode.java
  src/main/java/org/hmanwon/domain/community/board/presentation/BoardController.java
  src/main/java/org/hmanwon/domain/community/comment/application/CommentService.java
  src/main/java/org/hmanwon/domain/community/comment/dto/response/CommentResponseDto.java
  src/main/java/org/hmanwon/domain/community/comment/exception/CommentExceptionCode.java
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/member/dto/response/MemberResponse.java
  src/main/java/org/hmanwon/domain/member/dto/response/MyBoardsResponseDto.java
  src/main/java/org/hmanwon/domain/member/dto/response/MyCommentResponseDto.java
  src/main/java/org/hmanwon/domain/member/dto/response/NicknameResponse.java
  src/main/java/org/hmanwon/domain/member/entity/Member.java
  src/main/java/org/hmanwon/domain/member/exception/MemberExceptionCode.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
  src/main/resources/application.yml
Labels: Type: Feature/Function

#26 feat: 내 게시글 조회 API 응답 DTO 변경
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
Labels: Type: Feature/Function, Type: Improvement

#25 refactor: 닉네임 유효성 검증 및 응답 메세지 수정
  src/main/java/org/hmanwon/domain/auth/presentation/AuthController.java
  src/main/java/org/hmanwon/domain/community/board/application/BoardService.java
  src/main/java/org/hmanwon/domain/community/comment/application/CommentService.java
  src/main/java/org/hmanwon/domain/community/comment/dto/request/CommentRequestDto.java
  src/main/java/org/hmanwon/domain/community/comment/dto/request/CommentUpdateRequestsDto.java
  src/main/java/org/hmanwon/domain/community/comment/presentation/CommentController.java
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
Labels: Type: Feature/Function

#22 feat: 가게 좋아요 상태 변경 API 구현
  src/main/java/org/hmanwon/domain/shop/application/ShopService.java
  src/main/java/org/hmanwon/domain/shop/dto/SeoulGoodShopDetailResponse.java
  src/main/java/org/hmanwon/domain/shop/dto/SeoulGoodShopResponse.java
  src/main/java/org/hmanwon/domain/shop/dto/ShopLikeRequest.java
  src/main/java/org/hmanwon/domain/shop/dto/ShopLikeResponse.java
  src/main/java/org/hmanwon/domain/shop/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/shop/exception/ShopExceptionCode.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
Labels: Type: Feature/Function

#29 [fix] msg -> message로 수정, 가게 상세 정보 수정, 상세 조회 부분 리스트 없앰
  src/main/java/org/hmanwon/domain/shop/application/ShopService.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/java/org/hmanwon/global/common/dto/ErrorResponseDTO.java
Labels: Type: Feature/Function, Type: Hotfix

#28 [init & fix] 서울 착한 업소 초기화 부분 수정
  src/main/java/org/hmanwon/domain/shop/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/shop/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/shop/init/util/KakaoApiUtil.java
Labels: Type: Feature/Function

#30 [refactor] 검색어 예외 처리 추가 및 글로벌 핸들러 변경
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/java/org/hmanwon/global/common/exception/DefaultExceptionHandler.java
Labels: Type: Feature/Function

#31 Feature/auth api 인증 서비스 보완
  src/main/java/org/hmanwon/domain/auth/application/AuthService.java
  src/main/java/org/hmanwon/domain/auth/application/JwtProvider.java
  src/main/java/org/hmanwon/domain/auth/exception/AuthException.java
  src/main/java/org/hmanwon/domain/auth/exception/AuthExceptionCode.java
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
  src/main/java/org/hmanwon/domain/shop/init/util/KakaoApiUtil.java
  src/main/java/org/hmanwon/global/common/exception/DefaultExceptionHandler.java
  src/main/resources/application.yml
Labels: Type: Feature/Function, Type: Improvement

#32 [Bugfix] 검색 기능 및 전체 조회 조건문 수정
  src/main/java/org/hmanwon/domain/shop/application/ShopService.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/test/java/org/hmanwon/http_test/display/select/shop-getAll-byCategory.http
  src/test/java/org/hmanwon/http_test/display/select/shop-getAll.http
  src/test/java/org/hmanwon/http_test/display/select/shop-search-byKeyword.http
  src/test/java/org/hmanwon/http_test/shop/select/shop-getAll-byCategory.http
  src/test/java/org/hmanwon/http_test/shop/select/shop-getAll.http
  src/test/java/org/hmanwon/http_test/shop/select/shop-getDetail.http
  src/test/java/org/hmanwon/http_test/shop/select/shop-search-byKeyword.http
Labels: Type: Bugfix/Function

#33 fix: 로그인 api GET으로 변경
  src/main/java/org/hmanwon/domain/auth/presentation/AuthController.java
Labels: Type: Hotfix

#34 fix: JWT 키 알고리즘 변경 및 secretKey 값 변경
  src/main/java/org/hmanwon/domain/auth/application/JwtProvider.java
  src/main/resources/application.yml
Labels: Type: Hotfix

#36 feat: 테스트용 회원 전체 목록 조회 API 구현
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
Labels: Type: Feature/Function

#37 [Feature] 게시글 생성만 일단 완료
  src/main/java/org/hmanwon/domain/community/board/application/BoardService.java
  src/main/java/org/hmanwon/domain/community/board/dto/request/BoardWriteRequest.java
  src/main/java/org/hmanwon/domain/community/board/entity/BoardHashtag.java
  src/main/java/org/hmanwon/infra/image/application/ImageUploader.java
  src/main/resources/application.yml
  src/test/java/org/hmanwon/http_test/community/board/insert/board-create.http
  src/test/java/org/hmanwon/http_test/community/board/insert/image-upload.http
  src/test/resources/6e42d0c6-f5cb-4799-9270-01fe89729b31.png
Labels: Type: Feature/Function

#38 feat: 토큰 유효성 검증 API 구현
  src/main/java/org/hmanwon/domain/auth/application/AuthService.java
  src/main/java/org/hmanwon/domain/auth/dto/TokenValidationResponse.java
  src/main/java/org/hmanwon/domain/auth/presentation/AuthController.java
Labels: Type: Feature/Function

#35 회원, 좋아요, 댓글 API에 JWT 적용
  src/main/java/org/hmanwon/domain/auth/application/AuthService.java
  src/main/java/org/hmanwon/domain/auth/application/JwtProvider.java
  src/main/java/org/hmanwon/domain/community/comment/presentation/CommentController.java
  src/main/java/org/hmanwon/domain/member/application/MemberService.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
Labels: Type: Feature/Function

#40 Feature/zzan 짠처리 로그인 회원 연결 완료, QR 이미지 배포 주소 변경
  src/main/java/org/hmanwon/domain/member/entity/Member.java
  src/main/java/org/hmanwon/domain/zzan/purchase/application/PurchaseService.java
  src/main/java/org/hmanwon/domain/zzan/purchase/presentation/PurchaseController.java
  src/main/java/org/hmanwon/domain/zzan/purchase/util/QRCodeUtil.java
Labels: Status: In Progress

#41 [Feature] 로그인 url로 변경
  src/main/java/org/hmanwon/domain/community/board/presentation/BoardController.java
Labels: Type: Feature/Function

#42 [Fix] 로그인 모두 해제
  src/main/java/org/hmanwon/domain/community/board/presentation/BoardController.java
  src/main/java/org/hmanwon/domain/community/comment/presentation/CommentController.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/java/org/hmanwon/domain/zzan/purchase/application/PurchaseService.java
  src/main/java/org/hmanwon/domain/zzan/purchase/presentation/PurchaseController.java
Labels: Type: Refactor, Type: Improvement

#43 fix: 카카오 redirectURL 변경
  src/main/java/org/hmanwon/domain/auth/application/AuthService.java
Labels: Type: Hotfix

#44 fix: QR CODE 이미지 링크 변경
  src/main/java/org/hmanwon/domain/zzan/purchase/application/PurchaseService.java
  src/main/java/org/hmanwon/domain/zzan/purchase/presentation/PurchaseController.java
Labels: Status: In Progress

#45 [Fix] 로그인 api로 변경
  src/main/java/org/hmanwon/domain/community/board/presentation/BoardController.java
  src/main/java/org/hmanwon/domain/community/comment/presentation/CommentController.java
  src/main/java/org/hmanwon/domain/member/presentation/MemberController.java
  src/main/java/org/hmanwon/domain/shop/presentation/ShopController.java
  src/main/java/org/hmanwon/domain/zzan/purchase/presentation/PurchaseController.java
Labels: Type: Feature/Function
