Repository happymanwon/Backend, pull requests merged in 2023-11, with the labels that each got.

#2 [Feature] security module 완료
  .gitignore
  build.gradle
  settings.gradle
  src/main/java/org/hmanwon/HManwonApplication.java
  src/main/java/org/hmanwon/domain/display/entity/Item.java
  src/main/java/org/hmanwon/domain/display/entity/Seoul_Good_Shop.java
  src/main/java/org/hmanwon/domain/user/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/user/entity/Member.java
  src/main/java/org/hmanwon/domain/zzan_purchase/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/zzan_purchase/entity/Member.java
  src/main/java/org/hmanwon/global/common/request.java
  src/main/java/org/hmanwon/global/common/response.java
  src/main/java/org/hmanwon/global/config/AuthorizationConfig.java
  src/main/java/org/hmanwon/global/config/exception/CustomAuthenticationEntryPoint.java
  src/main/java/org/hmanwon/global/config/jwt/JwtKey.java
  src/main/java/org/hmanwon/global/config/jwt/JwtProperties.java
  src/main/java/org/hmanwon/global/config/jwt/JwtTokenFilter.java
  src/main/java/org/hmanwon/global/config/jwt/SigningKeyResolver.java
  src/main/java/org/hmanwon/global/config/util/JwtTokenUtils.java
  src/main/resources/application.yml
Labels: Type: Feature/Function, Type: Question

#4 [feat & init] 스프링 실행되면 바로 데이터 올릴 수 있도록 했습니다 + 패키지 초기화
  build.gradle
  src/main/java/org/hmanwon/HManwonApplication.java
  src/main/java/org/hmanwon/domain/display/dao/ItemRepository.java
  src/main/java/org/hmanwon/domain/display/dao/SeoulGoodShopRepository.java
  src/main/java/org/hmanwon/domain/display/entity/Item.java
  src/main/java/org/hmanwon/domain/display/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/display/entity/Seoul_Good_Shop.java
  src/main/java/org/hmanwon/domain/display/exception/DisplayException.java
  src/main/java/org/hmanwon/domain/display/exception/DisplayExceptionCode.java
  src/main/java/org/hmanwon/domain/display/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/display/init/dto/FirstJsonReadDTO.java
  src/main/java/org/hmanwon/domain/display/init/dto/ItemDTO.java
  src/main/java/org/hmanwon/domain/display/init/dto/SeoulGoodShopDTO.java
  src/main/java/org/hmanwon/domain/display/init/exception/InitDisplayException.java
  src/main/java/org/hmanwon/domain/display/init/exception/InitDisplayExceptionCode.java
  src/main/java/org/hmanwon/domain/display/init/util/AddressToCodeConverter.java
  src/main/java/org/hmanwon/domain/zzan_purchase/dao/MemberRepository.java
  src/main/java/org/hmanwon/global/common/dto/ErrorResponseDTO.java
  src/main/java/org/hmanwon/global/common/dto/ResponseDTO.java
  src/main/java/org/hmanwon/global/common/exception/DefaultException.java
  src/main/java/org/hmanwon/global/common/exception/DefaultExceptionCode.java
  src/main/java/org/hmanwon/global/common/exception/DefaultExceptionHandler.java
  src/main/java/org/hmanwon/global/common/exception/ExceptionCode.java
  src/main/java/org/hmanwon/global/config/AuthorizationConfig.java
  src/main/java/org/hmanwon/global/config/exception/CustomAuthenticationEntryPoint.java
  src/main/java/org/hmanwon/global/config/jwt/JwtKey.java
  src/main/java/org/hmanwon/global/config/jwt/JwtTokenFilter.java
  src/main/java/org/hmanwon/global/config/jwt/SigningKeyResolver.java
  src/main/java/org/hmanwon/global/config/util/JwtTokenUtils.java
  src/main/resources/application.yml
  src/main/resources/seoul_good_shop.json
Labels: Type: Feature/Function

#6 [Feature] Json 데이터 정형화 & StoreDetail 기능 추가
  src/main/java/org/hmanwon/domain/display/api/DisplayController.java
  src/main/java/org/hmanwon/domain/display/application/DisplayService.java
  src/main/java/org/hmanwon/domain/display/dao/ItemRepository.java
  src/main/java/org/hmanwon/domain/display/dao/SeoulGoodShopRepository.java
  src/main/java/org/hmanwon/domain/display/dto/MenuResponse.java
  src/main/java/org/hmanwon/domain/display/dto/SeoulGoodShopDetailResponse.java
  src/main/java/org/hmanwon/domain/display/dto/SeoulGoodShopResponse.java
  src/main/java/org/hmanwon/domain/display/entity/Menu.java
  src/main/java/org/hmanwon/domain/display/entity/SeoulGoodShop.java
  src/main/java/org/hmanwon/domain/display/init/application/InitSeoulGoodShopService.java
  src/main/java/org/hmanwon/domain/display/init/dto/SeoulGoodShopDTO.java
  src/main/java/org/hmanwon/global/config/WebConfigure.java
  src/main/resources/application.yml
  src/main/resources/seoul_good_shop.json
Labels: Type: Feature/Function

#8 [Refactor] Json 데이터 수정
  src/main/resources/seoul_good_shop.json
Labels: Type: Refactor

#9 [Feature] Member와 Communtiy(Board,Comment) 엔터티 초안 완성
  src/main/java/org/hmanwon/domain/community/board/entity/Board.java
  src/main/java/org/hmanwon/domain/community/comment/entity/Comment.java
  src/main/java/org/hmanwon/domain/member/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/member/entity/Member.java
  src/main/java/org/hmanwon/domain/user/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/user/entity/Member.java
  src/main/java/org/hmanwon/domain/zzan_purchase/dao/MemberRepository.java
  src/main/java/org/hmanwon/domain/zzan_purchase/entity/Member.java
Labels: Type: Feature/Function, Type: Question

#11 [Feature] 검색 기능 완성했습니다.
  src/main/java/org/hmanwon/HManwonApplication.java
  src/main/java/org/hmanwon/domain/display/application/DisplayService.java
  src/main/java/org/hmanwon/domain/display/dao/SeoulGoodShopRepository.java
  src/main/java/org/hmanwon/domain/display/presentation/DisplayController.java
  src/main/java/org/hmanwon/global/config/AppConfig.java
  src/main/java/org/hmanwon/global/config/WebConfig.java
  src/test/java/org/hmanwon/http_test/display/select/shop-getAll.http
  src/test/java/org/hmanwon/http_test/display/select/shop-search-byKeyword.http
Labels: Type: Feature/Function
